# handler3.yaml
---
- name: Handlers Example3
  hosts: serverb.example.com
  gather_facts: false
  become: true
  vars:
    pkg: vsftpd
  tasks:
    - name: Install vsftpd
      yum:
        name: "{{ pkg }}"
        state: latest

    - name: Installing vsftpd
      debug:
        msg: "restarting vsftp"
      changed_when: true           
      notify: restart vsftpd

  handlers:
    - name: "restart {{ pkg | default('vsftpd')}}"
      debug:
        msg: "Restarting {{ pkg | default('vsftpd')}}"
